Just some scrap paper

In [7]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
from pylab import *
from spylind import spyIVP as sivp
from spylind import spylind as spl
import sympy as sm

from spylind import spylind as spl # master equation useful bits
import qutip as q
sm.init_printing()

# For testing/debuggin:
if 1:
    import MT 
    from MT import liouvillian as L
    import pdb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Copying pyMBE

In [12]:
#
H0, [EinS, H1], [DeltaS, Hdet], c_opL=sld.makeBlochOperators(gsEnergies= [0,1], esEnergies=[0], osc_strengths=np.array([[1],[1]]) ,
                        T1_opt=2)
H_desc = [H0, (EinS, dest), (sm.conjugate(EinS), dest.H), (DeltaS, Hdet) ]


In [13]:
H1

matrix([[0, 0, 0.5*conjugate(Ef)],
        [0, 0, 0.5*conjugate(Ef)],
        [0.5*Ef, 0.5*Ef, 0]], dtype=object)

In [15]:
H1a

matrix([[0, 0, 0],
        [0, 0, 0],
        [0.500000000000000, 0.500000000000000, 0]], dtype=object)

In [18]:
zS = sm.symbols("z, ")
H1a = np.matrix(sm.Matrix(np.tril(H1, 0)).subs(EinS,1))
H1b = H1a.T.conj()
H_desc = [H0, [EinS, H1a], [ sm.conjugate(EinS), H1b], (DeltaS, Hdet) ]
display(H_desc[0], c_opL, H1a, H1b)

matrix([[ 0.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j, -6.28318531+0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j]])

[matrix([[0, 0, 0.707106781186548],
         [0, 0, 0],
         [0, 0, 0]], dtype=object),
 matrix([[0, 0, 0],
         [0, 0, 0.707106781186548],
         [0, 0, 0]], dtype=object)]

matrix([[0, 0, 0],
        [0, 0, 0],
        [0.500000000000000, 0.500000000000000, 0]], dtype=object)

matrix([[0, 0, 0.500000000000000],
        [0, 0, 0.500000000000000],
        [0, 0, 0]], dtype=object)

In [17]:
eq, ex_vals=spl.makeMESymb(H_desc, c_opL=c_opL, e_opL = [H1a], bReturnMatrixEquation=True)
display(eq, ex_vals)

                                       ⎡                                      
⎡\rho_{0|0}  \rho_{0|1}  \rho_{0|2}⎤   ⎢                      0.5⋅ⅈ⋅\rho_{0|2}
⎢                                  ⎥   ⎢                                      
⎢__________                        ⎥   ⎢                                ⎛___  
⎢\rho_{0|1}  \rho_{1|1}  \rho_{1|2}⎥ = ⎢               0.5⋅ⅈ⋅\rho_{1|2}⋅⎝Eₑₓ +
⎢                                  ⎥   ⎢                                      
⎢__________  __________            ⎥   ⎢                   ⎛___   __⎞         
⎣\rho_{0|2}  \rho_{1|2}  \rho_{2|2}⎦   ⎣- 0.5⋅ⅈ⋅\rho_{0|0}⋅⎝Eₑₓ + Ef⎠ + 0.5⋅ⅈ⋅

 ⎛___   __⎞                                     __________                    
⋅⎝Eₑₓ + Ef⎠ + 0.5⋅\rho_{2|2} - 0.5⋅ⅈ⋅(Eₑₓ + Ef)⋅\rho_{0|2}                    
                                                                              
 __⎞                    __________                      __________            
 Ef⎠ - 0.5⋅ⅈ⋅(Eₑₓ + Ef)⋅\rho_{0|2} + 6.283185307179