Just some scrap paper

In [20]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
from pylab import *
from spylind import spyIVP as so
import sympy as sm

from spylind import spylind as spl # master equation useful bits
import qutip as q
sm.init_printing()

# For testing/debuggin:
if 1:
    import MT 
    from MT import liouvillian as L
    import pdb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Copying pyMBE

In [14]:
H0, [Esym, H1], Hlst, c_opL = spl.constructBlochHamiltonian(gsEnergies=[-1,1], esEnergies=[0], osc_strengths=np.array([[1],[1]]),
                        T1_opt=10)

In [18]:
H0, [EinS, H1a], ([DeltaS, Hdet]), c_opL = h.constructBlochHamiltonian([0,1], [0], osc_strengths=1,
                        T1_opt=1, br_ratio=[1,1])

In [22]:
zS, EexS = sm.symbols("z, E_ex")
H1a = np.matrix(sm.Matrix(np.tril(H1a, 0)).subs(EinS,1))
H1b = H1a.T.conj()
H_desc = [H0, [EexS+EinS, H1a], [sm.conjugate(EexS) + sm.conjugate(EinS), H1b], (DeltaS, Hdet) ]
display(H_desc[0], c_opL, H1a, H1b)

matrix([[ 0.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j, -6.28318531+0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j]])

[matrix([[0, 0, 1.00000000000000],
         [0, 0, 0],
         [0, 0, 0]], dtype=object),
 matrix([[0, 0, 0],
         [0, 0, 1.00000000000000],
         [0, 0, 0]], dtype=object)]

matrix([[0, 0, 0],
        [0, 0, 0],
        [0.500000000000000, 0.500000000000000, 0]], dtype=object)

matrix([[0, 0, 0.500000000000000],
        [0, 0, 0.500000000000000],
        [0, 0, 0]], dtype=object)

In [23]:
eq, ex_vals=h.makeMESymb(H_desc, c_opL=c_opL, e_opL = [H1a], bReturnMatrixEquation=True)
display(eq, ex_vals)

makeMESymb enter


                                       ⎡                                      
⎡\rho_{0|0}  \rho_{0|1}  \rho_{0|2}⎤   ⎢                    - 0.5⋅ⅈ⋅\rho_{0|2}
⎢                                  ⎥   ⎢                                      
⎢__________                        ⎥   ⎢                               ⎛___   
⎢\rho_{0|1}  \rho_{1|1}  \rho_{1|2}⎥ = ⎢            - 0.5⋅ⅈ⋅\rho_{1|2}⋅⎝Eₑₓ + 
⎢                                  ⎥   ⎢                                      
⎢__________  __________            ⎥   ⎢                 ⎛___   __⎞           
⎣\rho_{0|2}  \rho_{1|2}  \rho_{2|2}⎦   ⎣0.5⋅ⅈ⋅\rho_{0|0}⋅⎝Eₑₓ + Ef⎠ - 0.5⋅ⅈ⋅\r

 ⎛___   __⎞                                     __________                    
⋅⎝Eₑₓ + Ef⎠ + 1.0⋅\rho_{2|2} + 0.5⋅ⅈ⋅(Eₑₓ + Ef)⋅\rho_{0|2}                    
                                                                              
__⎞                    __________                      __________             
Ef⎠ + 0.5⋅ⅈ⋅(Eₑₓ + Ef)⋅\rho_{0|2} - 6.2831853071795